apiVersion: apps/v1
kind: deployment
metadata:
  name: chess-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-chess-game
  template:
    metadata:
      labels:
        app: my-chess-game
    spec:
      containers:
        -name: chess-application
        image: rahul0003/chessgame
        ports:
          -containerPort: 3000 
        env:
          - name: DATABASE_URL
            valueFrom:
            secretKeyRef:
              name: secret-values
              key: DATABASE_URL  

        -name:  postgres 
        image: postgres
        ports:
          containerPort: 5432   
        env:
          - name: POSTGRES_DB
            valueFrom:
            configMapKeyRef:
              name: chess-app-config
              key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
            configMapKeyRef:
              name: chess-app-config
              key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
              name: secret-values
              key: POSTGRES_PASSWORD  
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
    volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: ebs-pvc        